@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjQzODU1NjYyLCJleHAiOjE2NDQwMjg0NjIsImF1ZCI6IjEiLCJpc3MiOiJvbm5ld3MuY29tLmNvIn0.wCIY1hVNoEMxTJ2iZSbHVR9e6WZresQl9dBF3Xmejjk
//@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmOTRjYzkyNmZlN2E0YzQ5ZjNmNmMwMiIsImlhdCI6MTYxMjY2MzA5NywiZXhwIjoxNjEyODM1ODk3LCJhdWQiOiI1Zjk0Y2M5MjZmZTdhNGM0OWYzZjZjMDIiLCJpc3MiOiJvbm5ld3MuY29tLmNvIn0.3VGaIEMO3n-A8XOnEDxGtabLE3S77pbPGahNT_D1tPs

###
POST http://localhost:3500/api/signin
Content-Type: application/json

{
	"username":"Admin",
    "password": "AdminStore123*",
    "role": ["Admin"]
}


###
POST http://localhost:3500/api/signup
Content-Type: application/json

{
	"username": "Admin",
    "password": "AdminStore123*",
    "password2": "AdminStore123*",
    "fullname": "Username",
    "email": "mavelasquezgi@unal.edu.co",
    "role": "Admin" 
}

###
POST http://localhost:3500/api/changepassword
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"currentPassword":"user*",
    "newPassword": "12345"
}

###  create category
POST http://localhost:3500/api/createcategory
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"name":"Entretenimiento",
    "descrip":"Entretenimiento"
}

###  update category
POST http://localhost:3500/api/updatecategory
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"id":3,
    "name":"test4",
    "descrip":"test4"
}

###  get categories
GET http://localhost:3500/api/categories
Authorization: Bearer {{token}}
Content-Type: application/json

###  get category
GET http://localhost:3500/api/category/Alimento
Authorization: Bearer {{token}}
Content-Type: application/json

###  delete category
GET http://localhost:3500/api/delcategory/test4
Authorization: Bearer {{token}}
Content-Type: application/json

###  create product 
POST http://localhost:3500/api/createproduct
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"name":"test1",
    "descrip":"test1",
    "category":"1",
    "price":"212",
    "wheigth":"123",
    "image": "path"
}

###  update product 
POST http://localhost:3500/api/updateproduct
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"id": 2,
    "name":"testUpdat",
    "descrip":"testUpdat",
    "category":"1",
    "price":"212",
    "wheigth":"123",
    "image": "/home/mauro/Documents/store/prodImages/82465c22-a717-4d51-b324-41edc2c0b5c2.png"
}

###  get products
GET http://localhost:3500/api/allproducts
Authorization: Bearer {{token}}
Content-Type: application/json

###  get product by id 
GET http://localhost:3500/api/product/4
Authorization: Bearer {{token}}
Content-Type: application/json

###  del product by id
GET http://localhost:3500/api/delproduct/4
Authorization: Bearer {{token}}
Content-Type: application/json

###  create order 
POST http://localhost:3500/api/createorder
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"user":1,
    "product":2,
    "units":2
}

###  del order by id
GET http://localhost:3500/api/delorder/1
Authorization: Bearer {{token}}
Content-Type: application/json

###  get all orders
GET http://localhost:3500/api/orders
Authorization: Bearer {{token}}
Content-Type: application/json